# Generated by Django 4.1.1 on 2022-09-15 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3',
            name='s3_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
