# Generated by Django 4.1.3 on 2022-11-21 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CombinedWords',
            new_name='CombinedWord',
        ),
        migrations.AlterModelOptions(
            name='combinedword',
            options={'verbose_name': 'CombinedWord', 'verbose_name_plural': 'CombinedWords'},
        ),
    ]
