# Generated by Django 4.1.1 on 2022-10-01 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3securityresult',
            name='s3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='security_result', to='S3.s3'),
            preserve_default=False,
        ),
    ]
