# Generated by Django 4.1.4 on 2022-12-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0002_rename_combinedwords_combinedword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3',
            name='combined_words',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='s3', to='S3.combinedword'),
        ),
        migrations.AlterField(
            model_name='s3',
            name='hashed_value',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hash',
                                       related_query_name='s3', to='S3.hash'),
        ),
    ]
