# Generated by Django 4.1.1 on 2022-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0002_s3_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3',
            name='s3_url',
            field=models.URLField(unique=True),
        ),
    ]
