# Generated by Django 4.1.1 on 2022-09-29 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0003_alter_s3_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3',
            name='s3_url',
            field=models.URLField(unique=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='s3',
            name='target_url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
