# Generated by Django 4.1.1 on 2022-10-02 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0003_alter_s3securityresult_s3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s3securityresult',
            options={'verbose_name': 'Security Result', 'verbose_name_plural': 'Security Results'},
        ),
    ]
