# Generated by Django 4.1.1 on 2022-10-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0005_remove_s3securityresult_s3_s3_security_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=100)),
                ('is_noun', models.BooleanField(default=True)),
            ],
        ),
    ]
