# Generated by Django 4.1.2 on 2022-10-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0006_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
