# Generated by Django 4.1.2 on 2022-10-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0007_alter_word_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_word',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_words',
                                   to='S3.word')),
                ('second_word',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_words',
                                   to='S3.word')),
            ],
        ),
        migrations.AddField(
            model_name='s3',
            name='combined_words',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='S3.combinedwords'),
        ),
    ]
