# Generated by Django 4.1.2 on 2022-10-23 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('S3', '0008_combinedwords_s3_combined_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedwords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
