# Generated by Django 4.1.1 on 2022-10-31 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0010_alter_s3_security_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('hash_value', models.CharField(max_length=1000)),
            ],
        ),
    ]
