# Generated by Django 4.1.1 on 2022-11-02 04:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0010_alter_s3_security_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField(validators=[django.core.validators.URLValidator])),
                ('hash_value', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='s3',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='s3',
            name='hash',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hash', to='S3.hash'),
        ),
    ]
