# Generated by Django 4.1.1 on 2022-11-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0011_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3',
            name='updated_at',
        ),
    ]
