# Generated by Django 4.1.1 on 2022-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('js_reqeust_time_UTC', models.DateTimeField()),
                ('page_loaded_time', models.DateTimeField()),
                ('page_leave_time', models.DateTimeField()),
                ('referer_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
