# Generated by Django 4.1.1 on 2022-09-05 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapturedUserData',
            new_name='CapturedData',
        ),
    ]
