# Generated by Django 4.1.1 on 2022-09-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_captureddata_city_captureddata_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureddata',
            name='city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='captureddata',
            name='country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
