# Generated by Django 4.1.1 on 2022-09-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('S3', '0003_alter_s3_s3_url'),
        ('analytics', '0004_alter_captureddata_city_alter_captureddata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureddata',
            name='s3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='captured_data', to='S3.s3'),
            preserve_default=False,
        ),
    ]
