# Generated by Django 4.1.1 on 2022-09-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0005_captureddata_s3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captureddata',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_visitors',
                                           to='analytics.captureddata')),
            ],
        ),
    ]
