# Generated by Django 4.1.1 on 2022-09-08 13:21

from django.db import migrations, models

import user_profile.models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=user_profile.models.upload_img),
        ),
    ]
